# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Ref https://github.com/flutter/packages/blob/master/packages/flutter_lints/lib/flutter.yaml
    # Ref https://dart-lang.github.io/linter/lints/
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - require_trailing_commas
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - cancel_subscriptions

    - avoid_empty_else
    - exhaustive_cases

    # just style suggestions
    - sort_pub_dependencies
    - use_rethrow_when_possible
    - prefer_single_quotes
    - directives_ordering
    - always_use_package_imports
    - sort_child_properties_last
    - unawaited_futures